// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tinylog/prototype.proto

package com.huimang.tinylog.proto;

public interface PrototypeLogQueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tinylog.prototype.v1.PrototypeLogQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
   * @return Whether the startTimestampMillis field is set.
   */
  boolean hasStartTimestampMillis();
  /**
   * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
   * @return The startTimestampMillis.
   */
  com.google.protobuf.UInt64Value getStartTimestampMillis();
  /**
   * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
   */
  com.google.protobuf.UInt64ValueOrBuilder getStartTimestampMillisOrBuilder();

  /**
   * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
   * @return Whether the endTimestampMillis field is set.
   */
  boolean hasEndTimestampMillis();
  /**
   * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
   * @return The endTimestampMillis.
   */
  com.google.protobuf.UInt64Value getEndTimestampMillis();
  /**
   * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
   */
  com.google.protobuf.UInt64ValueOrBuilder getEndTimestampMillisOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
   * @return Whether the minimumLevel field is set.
   */
  boolean hasMinimumLevel();
  /**
   * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
   * @return The minimumLevel.
   */
  com.google.protobuf.Int32Value getMinimumLevel();
  /**
   * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getMinimumLevelOrBuilder();

  /**
   * <code>.google.protobuf.StringValue keyword = 4;</code>
   * @return Whether the keyword field is set.
   */
  boolean hasKeyword();
  /**
   * <code>.google.protobuf.StringValue keyword = 4;</code>
   * @return The keyword.
   */
  com.google.protobuf.StringValue getKeyword();
  /**
   * <code>.google.protobuf.StringValue keyword = 4;</code>
   */
  com.google.protobuf.StringValueOrBuilder getKeywordOrBuilder();
}
