// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tinylog/prototype.proto

package com.huimang.tinylog.proto;

/**
 * <pre>
 * Defines one language-neutral log query contract.
 * </pre>
 *
 * Protobuf type {@code tinylog.prototype.v1.PrototypeLogQuery}
 */
public  final class PrototypeLogQuery extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tinylog.prototype.v1.PrototypeLogQuery)
    PrototypeLogQueryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PrototypeLogQuery.newBuilder() to construct.
  private PrototypeLogQuery(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PrototypeLogQuery() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PrototypeLogQuery();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PrototypeLogQuery(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.UInt64Value.Builder subBuilder = null;
            if (startTimestampMillis_ != null) {
              subBuilder = startTimestampMillis_.toBuilder();
            }
            startTimestampMillis_ = input.readMessage(com.google.protobuf.UInt64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startTimestampMillis_);
              startTimestampMillis_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.UInt64Value.Builder subBuilder = null;
            if (endTimestampMillis_ != null) {
              subBuilder = endTimestampMillis_.toBuilder();
            }
            endTimestampMillis_ = input.readMessage(com.google.protobuf.UInt64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endTimestampMillis_);
              endTimestampMillis_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (minimumLevel_ != null) {
              subBuilder = minimumLevel_.toBuilder();
            }
            minimumLevel_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(minimumLevel_);
              minimumLevel_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (keyword_ != null) {
              subBuilder = keyword_.toBuilder();
            }
            keyword_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(keyword_);
              keyword_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.huimang.tinylog.proto.TinylogPrototypeProto.internal_static_tinylog_prototype_v1_PrototypeLogQuery_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.huimang.tinylog.proto.TinylogPrototypeProto.internal_static_tinylog_prototype_v1_PrototypeLogQuery_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.huimang.tinylog.proto.PrototypeLogQuery.class, com.huimang.tinylog.proto.PrototypeLogQuery.Builder.class);
  }

  public static final int START_TIMESTAMP_MILLIS_FIELD_NUMBER = 1;
  private com.google.protobuf.UInt64Value startTimestampMillis_;
  /**
   * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
   * @return Whether the startTimestampMillis field is set.
   */
  public boolean hasStartTimestampMillis() {
    return startTimestampMillis_ != null;
  }
  /**
   * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
   * @return The startTimestampMillis.
   */
  public com.google.protobuf.UInt64Value getStartTimestampMillis() {
    return startTimestampMillis_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : startTimestampMillis_;
  }
  /**
   * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
   */
  public com.google.protobuf.UInt64ValueOrBuilder getStartTimestampMillisOrBuilder() {
    return getStartTimestampMillis();
  }

  public static final int END_TIMESTAMP_MILLIS_FIELD_NUMBER = 2;
  private com.google.protobuf.UInt64Value endTimestampMillis_;
  /**
   * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
   * @return Whether the endTimestampMillis field is set.
   */
  public boolean hasEndTimestampMillis() {
    return endTimestampMillis_ != null;
  }
  /**
   * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
   * @return The endTimestampMillis.
   */
  public com.google.protobuf.UInt64Value getEndTimestampMillis() {
    return endTimestampMillis_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : endTimestampMillis_;
  }
  /**
   * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
   */
  public com.google.protobuf.UInt64ValueOrBuilder getEndTimestampMillisOrBuilder() {
    return getEndTimestampMillis();
  }

  public static final int MINIMUM_LEVEL_FIELD_NUMBER = 3;
  private com.google.protobuf.Int32Value minimumLevel_;
  /**
   * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
   * @return Whether the minimumLevel field is set.
   */
  public boolean hasMinimumLevel() {
    return minimumLevel_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
   * @return The minimumLevel.
   */
  public com.google.protobuf.Int32Value getMinimumLevel() {
    return minimumLevel_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : minimumLevel_;
  }
  /**
   * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getMinimumLevelOrBuilder() {
    return getMinimumLevel();
  }

  public static final int KEYWORD_FIELD_NUMBER = 4;
  private com.google.protobuf.StringValue keyword_;
  /**
   * <code>.google.protobuf.StringValue keyword = 4;</code>
   * @return Whether the keyword field is set.
   */
  public boolean hasKeyword() {
    return keyword_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue keyword = 4;</code>
   * @return The keyword.
   */
  public com.google.protobuf.StringValue getKeyword() {
    return keyword_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : keyword_;
  }
  /**
   * <code>.google.protobuf.StringValue keyword = 4;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getKeywordOrBuilder() {
    return getKeyword();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startTimestampMillis_ != null) {
      output.writeMessage(1, getStartTimestampMillis());
    }
    if (endTimestampMillis_ != null) {
      output.writeMessage(2, getEndTimestampMillis());
    }
    if (minimumLevel_ != null) {
      output.writeMessage(3, getMinimumLevel());
    }
    if (keyword_ != null) {
      output.writeMessage(4, getKeyword());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startTimestampMillis_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStartTimestampMillis());
    }
    if (endTimestampMillis_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndTimestampMillis());
    }
    if (minimumLevel_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMinimumLevel());
    }
    if (keyword_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getKeyword());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.huimang.tinylog.proto.PrototypeLogQuery)) {
      return super.equals(obj);
    }
    com.huimang.tinylog.proto.PrototypeLogQuery other = (com.huimang.tinylog.proto.PrototypeLogQuery) obj;

    if (hasStartTimestampMillis() != other.hasStartTimestampMillis()) return false;
    if (hasStartTimestampMillis()) {
      if (!getStartTimestampMillis()
          .equals(other.getStartTimestampMillis())) return false;
    }
    if (hasEndTimestampMillis() != other.hasEndTimestampMillis()) return false;
    if (hasEndTimestampMillis()) {
      if (!getEndTimestampMillis()
          .equals(other.getEndTimestampMillis())) return false;
    }
    if (hasMinimumLevel() != other.hasMinimumLevel()) return false;
    if (hasMinimumLevel()) {
      if (!getMinimumLevel()
          .equals(other.getMinimumLevel())) return false;
    }
    if (hasKeyword() != other.hasKeyword()) return false;
    if (hasKeyword()) {
      if (!getKeyword()
          .equals(other.getKeyword())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartTimestampMillis()) {
      hash = (37 * hash) + START_TIMESTAMP_MILLIS_FIELD_NUMBER;
      hash = (53 * hash) + getStartTimestampMillis().hashCode();
    }
    if (hasEndTimestampMillis()) {
      hash = (37 * hash) + END_TIMESTAMP_MILLIS_FIELD_NUMBER;
      hash = (53 * hash) + getEndTimestampMillis().hashCode();
    }
    if (hasMinimumLevel()) {
      hash = (37 * hash) + MINIMUM_LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getMinimumLevel().hashCode();
    }
    if (hasKeyword()) {
      hash = (37 * hash) + KEYWORD_FIELD_NUMBER;
      hash = (53 * hash) + getKeyword().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.huimang.tinylog.proto.PrototypeLogQuery parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.huimang.tinylog.proto.PrototypeLogQuery parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.huimang.tinylog.proto.PrototypeLogQuery parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.huimang.tinylog.proto.PrototypeLogQuery parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.huimang.tinylog.proto.PrototypeLogQuery parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.huimang.tinylog.proto.PrototypeLogQuery parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.huimang.tinylog.proto.PrototypeLogQuery parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.huimang.tinylog.proto.PrototypeLogQuery parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.huimang.tinylog.proto.PrototypeLogQuery parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.huimang.tinylog.proto.PrototypeLogQuery parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.huimang.tinylog.proto.PrototypeLogQuery parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.huimang.tinylog.proto.PrototypeLogQuery parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.huimang.tinylog.proto.PrototypeLogQuery prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Defines one language-neutral log query contract.
   * </pre>
   *
   * Protobuf type {@code tinylog.prototype.v1.PrototypeLogQuery}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tinylog.prototype.v1.PrototypeLogQuery)
      com.huimang.tinylog.proto.PrototypeLogQueryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.huimang.tinylog.proto.TinylogPrototypeProto.internal_static_tinylog_prototype_v1_PrototypeLogQuery_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.huimang.tinylog.proto.TinylogPrototypeProto.internal_static_tinylog_prototype_v1_PrototypeLogQuery_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.huimang.tinylog.proto.PrototypeLogQuery.class, com.huimang.tinylog.proto.PrototypeLogQuery.Builder.class);
    }

    // Construct using com.huimang.tinylog.proto.PrototypeLogQuery.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (startTimestampMillisBuilder_ == null) {
        startTimestampMillis_ = null;
      } else {
        startTimestampMillis_ = null;
        startTimestampMillisBuilder_ = null;
      }
      if (endTimestampMillisBuilder_ == null) {
        endTimestampMillis_ = null;
      } else {
        endTimestampMillis_ = null;
        endTimestampMillisBuilder_ = null;
      }
      if (minimumLevelBuilder_ == null) {
        minimumLevel_ = null;
      } else {
        minimumLevel_ = null;
        minimumLevelBuilder_ = null;
      }
      if (keywordBuilder_ == null) {
        keyword_ = null;
      } else {
        keyword_ = null;
        keywordBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.huimang.tinylog.proto.TinylogPrototypeProto.internal_static_tinylog_prototype_v1_PrototypeLogQuery_descriptor;
    }

    @java.lang.Override
    public com.huimang.tinylog.proto.PrototypeLogQuery getDefaultInstanceForType() {
      return com.huimang.tinylog.proto.PrototypeLogQuery.getDefaultInstance();
    }

    @java.lang.Override
    public com.huimang.tinylog.proto.PrototypeLogQuery build() {
      com.huimang.tinylog.proto.PrototypeLogQuery result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.huimang.tinylog.proto.PrototypeLogQuery buildPartial() {
      com.huimang.tinylog.proto.PrototypeLogQuery result = new com.huimang.tinylog.proto.PrototypeLogQuery(this);
      if (startTimestampMillisBuilder_ == null) {
        result.startTimestampMillis_ = startTimestampMillis_;
      } else {
        result.startTimestampMillis_ = startTimestampMillisBuilder_.build();
      }
      if (endTimestampMillisBuilder_ == null) {
        result.endTimestampMillis_ = endTimestampMillis_;
      } else {
        result.endTimestampMillis_ = endTimestampMillisBuilder_.build();
      }
      if (minimumLevelBuilder_ == null) {
        result.minimumLevel_ = minimumLevel_;
      } else {
        result.minimumLevel_ = minimumLevelBuilder_.build();
      }
      if (keywordBuilder_ == null) {
        result.keyword_ = keyword_;
      } else {
        result.keyword_ = keywordBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.huimang.tinylog.proto.PrototypeLogQuery) {
        return mergeFrom((com.huimang.tinylog.proto.PrototypeLogQuery)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.huimang.tinylog.proto.PrototypeLogQuery other) {
      if (other == com.huimang.tinylog.proto.PrototypeLogQuery.getDefaultInstance()) return this;
      if (other.hasStartTimestampMillis()) {
        mergeStartTimestampMillis(other.getStartTimestampMillis());
      }
      if (other.hasEndTimestampMillis()) {
        mergeEndTimestampMillis(other.getEndTimestampMillis());
      }
      if (other.hasMinimumLevel()) {
        mergeMinimumLevel(other.getMinimumLevel());
      }
      if (other.hasKeyword()) {
        mergeKeyword(other.getKeyword());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.huimang.tinylog.proto.PrototypeLogQuery parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.huimang.tinylog.proto.PrototypeLogQuery) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.UInt64Value startTimestampMillis_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> startTimestampMillisBuilder_;
    /**
     * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
     * @return Whether the startTimestampMillis field is set.
     */
    public boolean hasStartTimestampMillis() {
      return startTimestampMillisBuilder_ != null || startTimestampMillis_ != null;
    }
    /**
     * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
     * @return The startTimestampMillis.
     */
    public com.google.protobuf.UInt64Value getStartTimestampMillis() {
      if (startTimestampMillisBuilder_ == null) {
        return startTimestampMillis_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : startTimestampMillis_;
      } else {
        return startTimestampMillisBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
     */
    public Builder setStartTimestampMillis(com.google.protobuf.UInt64Value value) {
      if (startTimestampMillisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startTimestampMillis_ = value;
        onChanged();
      } else {
        startTimestampMillisBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
     */
    public Builder setStartTimestampMillis(
        com.google.protobuf.UInt64Value.Builder builderForValue) {
      if (startTimestampMillisBuilder_ == null) {
        startTimestampMillis_ = builderForValue.build();
        onChanged();
      } else {
        startTimestampMillisBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
     */
    public Builder mergeStartTimestampMillis(com.google.protobuf.UInt64Value value) {
      if (startTimestampMillisBuilder_ == null) {
        if (startTimestampMillis_ != null) {
          startTimestampMillis_ =
            com.google.protobuf.UInt64Value.newBuilder(startTimestampMillis_).mergeFrom(value).buildPartial();
        } else {
          startTimestampMillis_ = value;
        }
        onChanged();
      } else {
        startTimestampMillisBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
     */
    public Builder clearStartTimestampMillis() {
      if (startTimestampMillisBuilder_ == null) {
        startTimestampMillis_ = null;
        onChanged();
      } else {
        startTimestampMillis_ = null;
        startTimestampMillisBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
     */
    public com.google.protobuf.UInt64Value.Builder getStartTimestampMillisBuilder() {
      
      onChanged();
      return getStartTimestampMillisFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
     */
    public com.google.protobuf.UInt64ValueOrBuilder getStartTimestampMillisOrBuilder() {
      if (startTimestampMillisBuilder_ != null) {
        return startTimestampMillisBuilder_.getMessageOrBuilder();
      } else {
        return startTimestampMillis_ == null ?
            com.google.protobuf.UInt64Value.getDefaultInstance() : startTimestampMillis_;
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value start_timestamp_millis = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> 
        getStartTimestampMillisFieldBuilder() {
      if (startTimestampMillisBuilder_ == null) {
        startTimestampMillisBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder>(
                getStartTimestampMillis(),
                getParentForChildren(),
                isClean());
        startTimestampMillis_ = null;
      }
      return startTimestampMillisBuilder_;
    }

    private com.google.protobuf.UInt64Value endTimestampMillis_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> endTimestampMillisBuilder_;
    /**
     * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
     * @return Whether the endTimestampMillis field is set.
     */
    public boolean hasEndTimestampMillis() {
      return endTimestampMillisBuilder_ != null || endTimestampMillis_ != null;
    }
    /**
     * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
     * @return The endTimestampMillis.
     */
    public com.google.protobuf.UInt64Value getEndTimestampMillis() {
      if (endTimestampMillisBuilder_ == null) {
        return endTimestampMillis_ == null ? com.google.protobuf.UInt64Value.getDefaultInstance() : endTimestampMillis_;
      } else {
        return endTimestampMillisBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
     */
    public Builder setEndTimestampMillis(com.google.protobuf.UInt64Value value) {
      if (endTimestampMillisBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endTimestampMillis_ = value;
        onChanged();
      } else {
        endTimestampMillisBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
     */
    public Builder setEndTimestampMillis(
        com.google.protobuf.UInt64Value.Builder builderForValue) {
      if (endTimestampMillisBuilder_ == null) {
        endTimestampMillis_ = builderForValue.build();
        onChanged();
      } else {
        endTimestampMillisBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
     */
    public Builder mergeEndTimestampMillis(com.google.protobuf.UInt64Value value) {
      if (endTimestampMillisBuilder_ == null) {
        if (endTimestampMillis_ != null) {
          endTimestampMillis_ =
            com.google.protobuf.UInt64Value.newBuilder(endTimestampMillis_).mergeFrom(value).buildPartial();
        } else {
          endTimestampMillis_ = value;
        }
        onChanged();
      } else {
        endTimestampMillisBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
     */
    public Builder clearEndTimestampMillis() {
      if (endTimestampMillisBuilder_ == null) {
        endTimestampMillis_ = null;
        onChanged();
      } else {
        endTimestampMillis_ = null;
        endTimestampMillisBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
     */
    public com.google.protobuf.UInt64Value.Builder getEndTimestampMillisBuilder() {
      
      onChanged();
      return getEndTimestampMillisFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
     */
    public com.google.protobuf.UInt64ValueOrBuilder getEndTimestampMillisOrBuilder() {
      if (endTimestampMillisBuilder_ != null) {
        return endTimestampMillisBuilder_.getMessageOrBuilder();
      } else {
        return endTimestampMillis_ == null ?
            com.google.protobuf.UInt64Value.getDefaultInstance() : endTimestampMillis_;
      }
    }
    /**
     * <code>.google.protobuf.UInt64Value end_timestamp_millis = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder> 
        getEndTimestampMillisFieldBuilder() {
      if (endTimestampMillisBuilder_ == null) {
        endTimestampMillisBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.UInt64Value, com.google.protobuf.UInt64Value.Builder, com.google.protobuf.UInt64ValueOrBuilder>(
                getEndTimestampMillis(),
                getParentForChildren(),
                isClean());
        endTimestampMillis_ = null;
      }
      return endTimestampMillisBuilder_;
    }

    private com.google.protobuf.Int32Value minimumLevel_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> minimumLevelBuilder_;
    /**
     * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
     * @return Whether the minimumLevel field is set.
     */
    public boolean hasMinimumLevel() {
      return minimumLevelBuilder_ != null || minimumLevel_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
     * @return The minimumLevel.
     */
    public com.google.protobuf.Int32Value getMinimumLevel() {
      if (minimumLevelBuilder_ == null) {
        return minimumLevel_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : minimumLevel_;
      } else {
        return minimumLevelBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
     */
    public Builder setMinimumLevel(com.google.protobuf.Int32Value value) {
      if (minimumLevelBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        minimumLevel_ = value;
        onChanged();
      } else {
        minimumLevelBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
     */
    public Builder setMinimumLevel(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (minimumLevelBuilder_ == null) {
        minimumLevel_ = builderForValue.build();
        onChanged();
      } else {
        minimumLevelBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
     */
    public Builder mergeMinimumLevel(com.google.protobuf.Int32Value value) {
      if (minimumLevelBuilder_ == null) {
        if (minimumLevel_ != null) {
          minimumLevel_ =
            com.google.protobuf.Int32Value.newBuilder(minimumLevel_).mergeFrom(value).buildPartial();
        } else {
          minimumLevel_ = value;
        }
        onChanged();
      } else {
        minimumLevelBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
     */
    public Builder clearMinimumLevel() {
      if (minimumLevelBuilder_ == null) {
        minimumLevel_ = null;
        onChanged();
      } else {
        minimumLevel_ = null;
        minimumLevelBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
     */
    public com.google.protobuf.Int32Value.Builder getMinimumLevelBuilder() {
      
      onChanged();
      return getMinimumLevelFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getMinimumLevelOrBuilder() {
      if (minimumLevelBuilder_ != null) {
        return minimumLevelBuilder_.getMessageOrBuilder();
      } else {
        return minimumLevel_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : minimumLevel_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value minimum_level = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getMinimumLevelFieldBuilder() {
      if (minimumLevelBuilder_ == null) {
        minimumLevelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getMinimumLevel(),
                getParentForChildren(),
                isClean());
        minimumLevel_ = null;
      }
      return minimumLevelBuilder_;
    }

    private com.google.protobuf.StringValue keyword_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> keywordBuilder_;
    /**
     * <code>.google.protobuf.StringValue keyword = 4;</code>
     * @return Whether the keyword field is set.
     */
    public boolean hasKeyword() {
      return keywordBuilder_ != null || keyword_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue keyword = 4;</code>
     * @return The keyword.
     */
    public com.google.protobuf.StringValue getKeyword() {
      if (keywordBuilder_ == null) {
        return keyword_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : keyword_;
      } else {
        return keywordBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue keyword = 4;</code>
     */
    public Builder setKeyword(com.google.protobuf.StringValue value) {
      if (keywordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        keyword_ = value;
        onChanged();
      } else {
        keywordBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue keyword = 4;</code>
     */
    public Builder setKeyword(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (keywordBuilder_ == null) {
        keyword_ = builderForValue.build();
        onChanged();
      } else {
        keywordBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue keyword = 4;</code>
     */
    public Builder mergeKeyword(com.google.protobuf.StringValue value) {
      if (keywordBuilder_ == null) {
        if (keyword_ != null) {
          keyword_ =
            com.google.protobuf.StringValue.newBuilder(keyword_).mergeFrom(value).buildPartial();
        } else {
          keyword_ = value;
        }
        onChanged();
      } else {
        keywordBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue keyword = 4;</code>
     */
    public Builder clearKeyword() {
      if (keywordBuilder_ == null) {
        keyword_ = null;
        onChanged();
      } else {
        keyword_ = null;
        keywordBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue keyword = 4;</code>
     */
    public com.google.protobuf.StringValue.Builder getKeywordBuilder() {
      
      onChanged();
      return getKeywordFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue keyword = 4;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getKeywordOrBuilder() {
      if (keywordBuilder_ != null) {
        return keywordBuilder_.getMessageOrBuilder();
      } else {
        return keyword_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : keyword_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue keyword = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getKeywordFieldBuilder() {
      if (keywordBuilder_ == null) {
        keywordBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getKeyword(),
                getParentForChildren(),
                isClean());
        keyword_ = null;
      }
      return keywordBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tinylog.prototype.v1.PrototypeLogQuery)
  }

  // @@protoc_insertion_point(class_scope:tinylog.prototype.v1.PrototypeLogQuery)
  private static final com.huimang.tinylog.proto.PrototypeLogQuery DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.huimang.tinylog.proto.PrototypeLogQuery();
  }

  public static com.huimang.tinylog.proto.PrototypeLogQuery getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PrototypeLogQuery>
      PARSER = new com.google.protobuf.AbstractParser<PrototypeLogQuery>() {
    @java.lang.Override
    public PrototypeLogQuery parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PrototypeLogQuery(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PrototypeLogQuery> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PrototypeLogQuery> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.huimang.tinylog.proto.PrototypeLogQuery getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

