// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tinylog/prototype.proto

package com.huimang.tinylog.proto;

public interface PrototypeLogRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tinylog.prototype.v1.PrototypeLogRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 timestamp_millis = 1;</code>
   * @return The timestampMillis.
   */
  long getTimestampMillis();

  /**
   * <code>.tinylog.prototype.v1.PrototypeLogLevel level = 2;</code>
   * @return The enum numeric value on the wire for level.
   */
  int getLevelValue();
  /**
   * <code>.tinylog.prototype.v1.PrototypeLogLevel level = 2;</code>
   * @return The level.
   */
  com.huimang.tinylog.proto.PrototypeLogLevel getLevel();

  /**
   * <code>string source = 3;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>string source = 3;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>string context = 4;</code>
   * @return The context.
   */
  java.lang.String getContext();
  /**
   * <code>string context = 4;</code>
   * @return The bytes for context.
   */
  com.google.protobuf.ByteString
      getContextBytes();

  /**
   * <code>string message = 5;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 5;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>map&lt;string, string&gt; attributes = 6;</code>
   */
  int getAttributesCount();
  /**
   * <code>map&lt;string, string&gt; attributes = 6;</code>
   */
  boolean containsAttributes(
      java.lang.String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttributes();
  /**
   * <code>map&lt;string, string&gt; attributes = 6;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttributesMap();
  /**
   * <code>map&lt;string, string&gt; attributes = 6;</code>
   */

  java.lang.String getAttributesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; attributes = 6;</code>
   */

  java.lang.String getAttributesOrThrow(
      java.lang.String key);
}
