// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tinylog/prototype.proto

package com.huimang.tinylog.proto;

/**
 * <pre>
 * Defines the shared severity contract used across TinyLog language implementations.
 * </pre>
 *
 * Protobuf enum {@code tinylog.prototype.v1.PrototypeLogLevel}
 */
public enum PrototypeLogLevel
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PROTOTYPE_LOG_LEVEL_UNSPECIFIED = 0;</code>
   */
  PROTOTYPE_LOG_LEVEL_UNSPECIFIED(0),
  /**
   * <code>PROTOTYPE_LOG_LEVEL_TRACE = 1;</code>
   */
  PROTOTYPE_LOG_LEVEL_TRACE(1),
  /**
   * <code>PROTOTYPE_LOG_LEVEL_DEBUG = 2;</code>
   */
  PROTOTYPE_LOG_LEVEL_DEBUG(2),
  /**
   * <code>PROTOTYPE_LOG_LEVEL_INFO = 3;</code>
   */
  PROTOTYPE_LOG_LEVEL_INFO(3),
  /**
   * <code>PROTOTYPE_LOG_LEVEL_WARN = 4;</code>
   */
  PROTOTYPE_LOG_LEVEL_WARN(4),
  /**
   * <code>PROTOTYPE_LOG_LEVEL_ERROR = 5;</code>
   */
  PROTOTYPE_LOG_LEVEL_ERROR(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PROTOTYPE_LOG_LEVEL_UNSPECIFIED = 0;</code>
   */
  public static final int PROTOTYPE_LOG_LEVEL_UNSPECIFIED_VALUE = 0;
  /**
   * <code>PROTOTYPE_LOG_LEVEL_TRACE = 1;</code>
   */
  public static final int PROTOTYPE_LOG_LEVEL_TRACE_VALUE = 1;
  /**
   * <code>PROTOTYPE_LOG_LEVEL_DEBUG = 2;</code>
   */
  public static final int PROTOTYPE_LOG_LEVEL_DEBUG_VALUE = 2;
  /**
   * <code>PROTOTYPE_LOG_LEVEL_INFO = 3;</code>
   */
  public static final int PROTOTYPE_LOG_LEVEL_INFO_VALUE = 3;
  /**
   * <code>PROTOTYPE_LOG_LEVEL_WARN = 4;</code>
   */
  public static final int PROTOTYPE_LOG_LEVEL_WARN_VALUE = 4;
  /**
   * <code>PROTOTYPE_LOG_LEVEL_ERROR = 5;</code>
   */
  public static final int PROTOTYPE_LOG_LEVEL_ERROR_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PrototypeLogLevel valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PrototypeLogLevel forNumber(int value) {
    switch (value) {
      case 0: return PROTOTYPE_LOG_LEVEL_UNSPECIFIED;
      case 1: return PROTOTYPE_LOG_LEVEL_TRACE;
      case 2: return PROTOTYPE_LOG_LEVEL_DEBUG;
      case 3: return PROTOTYPE_LOG_LEVEL_INFO;
      case 4: return PROTOTYPE_LOG_LEVEL_WARN;
      case 5: return PROTOTYPE_LOG_LEVEL_ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PrototypeLogLevel>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PrototypeLogLevel> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PrototypeLogLevel>() {
          public PrototypeLogLevel findValueByNumber(int number) {
            return PrototypeLogLevel.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.huimang.tinylog.proto.TinylogPrototypeProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final PrototypeLogLevel[] VALUES = values();

  public static PrototypeLogLevel valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PrototypeLogLevel(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:tinylog.prototype.v1.PrototypeLogLevel)
}

