// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tinylog/prototype.proto

package com.huimang.tinylog.proto;

public final class TinylogPrototypeProto {
  private TinylogPrototypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tinylog_prototype_v1_PrototypeLogRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tinylog_prototype_v1_PrototypeLogRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tinylog_prototype_v1_PrototypeLogRecord_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tinylog_prototype_v1_PrototypeLogRecord_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tinylog_prototype_v1_PrototypeLogQuery_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tinylog_prototype_v1_PrototypeLogQuery_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027tinylog/prototype.proto\022\024tinylog.proto" +
      "type.v1\032\036google/protobuf/wrappers.proto\"" +
      "\231\002\n\022PrototypeLogRecord\022\030\n\020timestamp_mill" +
      "is\030\001 \001(\004\0226\n\005level\030\002 \001(\0162\'.tinylog.protot" +
      "ype.v1.PrototypeLogLevel\022\016\n\006source\030\003 \001(\t" +
      "\022\017\n\007context\030\004 \001(\t\022\017\n\007message\030\005 \001(\t\022L\n\nat" +
      "tributes\030\006 \003(\01328.tinylog.prototype.v1.Pr" +
      "ototypeLogRecord.AttributesEntry\0321\n\017Attr" +
      "ibutesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:" +
      "\0028\001\"\360\001\n\021PrototypeLogQuery\022<\n\026start_times" +
      "tamp_millis\030\001 \001(\0132\034.google.protobuf.UInt" +
      "64Value\022:\n\024end_timestamp_millis\030\002 \001(\0132\034." +
      "google.protobuf.UInt64Value\0222\n\rminimum_l" +
      "evel\030\003 \001(\0132\033.google.protobuf.Int32Value\022" +
      "-\n\007keyword\030\004 \001(\0132\034.google.protobuf.Strin" +
      "gValue*\321\001\n\021PrototypeLogLevel\022#\n\037PROTOTYP" +
      "E_LOG_LEVEL_UNSPECIFIED\020\000\022\035\n\031PROTOTYPE_L" +
      "OG_LEVEL_TRACE\020\001\022\035\n\031PROTOTYPE_LOG_LEVEL_" +
      "DEBUG\020\002\022\034\n\030PROTOTYPE_LOG_LEVEL_INFO\020\003\022\034\n" +
      "\030PROTOTYPE_LOG_LEVEL_WARN\020\004\022\035\n\031PROTOTYPE" +
      "_LOG_LEVEL_ERROR\020\005B4\n\031com.huimang.tinylo" +
      "g.protoB\025TinylogPrototypeProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_tinylog_prototype_v1_PrototypeLogRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tinylog_prototype_v1_PrototypeLogRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tinylog_prototype_v1_PrototypeLogRecord_descriptor,
        new java.lang.String[] { "TimestampMillis", "Level", "Source", "Context", "Message", "Attributes", });
    internal_static_tinylog_prototype_v1_PrototypeLogRecord_AttributesEntry_descriptor =
      internal_static_tinylog_prototype_v1_PrototypeLogRecord_descriptor.getNestedTypes().get(0);
    internal_static_tinylog_prototype_v1_PrototypeLogRecord_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tinylog_prototype_v1_PrototypeLogRecord_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_tinylog_prototype_v1_PrototypeLogQuery_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tinylog_prototype_v1_PrototypeLogQuery_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tinylog_prototype_v1_PrototypeLogQuery_descriptor,
        new java.lang.String[] { "StartTimestampMillis", "EndTimestampMillis", "MinimumLevel", "Keyword", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
